apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube8s
  labels:
    app: helloworld
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      type: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: helloworld
        type: backend
    spec:
      containers:
      - name: welcome
        image: obdev/vod-front
        ports:
        - containerPort: 80
        imagePullPolicy: Always
